version: '3.4'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: academy
      POSTGRES_PASSWORD: academy
      POSTGRES_DB: citybike
    build:
      context: ./postgres
      dockerfile: Dockerfile
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080
  express:
    build:
      context: ./backend
    ports:
      - 3000:3000
    depends_on:
      - db
  vite_docker:
    build:
      context: ./frontend
    ports:
      - 5173:5173
    depends_on:
      - express
      